spring:
  profiles:
    active: dev
  main:
    web-application-type: none
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      properties:
        linger.ms: 1
    consumer:
      group-id: postman
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    topic:
      stock-data: datasource.gta.stockdata
      transaction: datasource.gta.transaction
      future-data: datasource.ctp.futuredata
      instrument: trader.ctp.instruments
app:
  connect:
    source:
      gta:
        active: false
        fens:
          - ip: 119.147.211.219
            port: 8866
          - ip: 119.147.211.220
            port: 8866
          - ip: 180.153.102.99
            port: 8888
          - ip: 180.153.102.94
            port: 8888
        username: ENC(jpco4xlJAKWZm0i0bOdEsQ==)
        password: ENC(bFNhLFQsGEyBPTb/fPznf4UmgwEdWUw3)
        subscriptions: SZSEL2_Quotation,SSEL2_Quotation
        codes: 600100,600243,600174
      tdf:
        active: false
        env:
          heart-beat-interval: 0
          missed-beart-count: 0
          open-time-out: 0
        host: 219.143.244.232
        port: 10021
        username: ENC(5WDU5rlVsw3jWt3ckpNAMA==)
        password: ENC(gGD9E8dBsK0AzCzbfDgPdg==)
        markets: SH-1-0;SZ-1-0
      ctp:
        ip: 180.168.146.187
        port: 10131
        active: true
        username: ENC(o1EqFfMkGiQKWoPgIblxGw==)
        password: ENC(BTsBaRC4LOtyv5smSqrMapczj3aL9rPH)
        broker-id: 9999
        subscriptions: au1912
    sink:
      kafka:
        active: false
      redis:
        active: true
    connector:
      - in: ctp
        out:
          - redis
    executor-service:
      type: fixed
      threads-number: 1
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD:}
